<a href="https://colab.research.google.com/github/chintanrout/Iris_prediction_using_ANN/blob/main/Iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
# Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd

In [68]:
# Loading Dataset
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",names = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)','Species'])
data.head()

sepal length (cm)  sepal width (cm)  ...  petal width (cm)      Species
0                5.1               3.5  ...               0.2  Iris-setosa
1                4.9               3.0  ...               0.2  Iris-setosa
2                4.7               3.2  ...               0.2  Iris-setosa
3                4.6               3.1  ...               0.2  Iris-setosa
4                5.0               3.6  ...               0.2  Iris-setosa

[5 rows x 5 columns]

In [69]:
X=data.iloc[:,:4].values
y=data.iloc[:,4].values

In [70]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [71]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [72]:
#encoding categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
y = labelencoder_X_1.fit_transform(y)

In [73]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [74]:
# Split Dataset
from sklearn.model_selection import train_test_split
x_train, x_test,  y_train, y_test = train_test_split(X, y, test_size=0.2)

In [75]:
# Data Shape
print(x_train.shape)
print(x_test.shape)

(120, 4)
(30, 4)


In [76]:
# Building the Model
model= Sequential()
model.add(Dense(100,input_shape=(4,), activation="relu"))
model.add(Dense(3, activation='softmax'))

In [77]:
# Compile the Model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [78]:
# Fit the Model
model.fit(x_train,y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 0s 4ms/step - loss: 1.1817 - accuracy: 0.3333
Epoch 2/20
4/4 [==============================] - 0s 5ms/step - loss: 1.0655 - accuracy: 0.3500
Epoch 3/20
4/4 [==============================] - 0s 7ms/step - loss: 0.9973 - accuracy: 0.5250
Epoch 4/20
4/4 [==============================] - 0s 5ms/step - loss: 0.9515 - accuracy: 0.5750
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 0.9013 - accuracy: 0.7917
Epoch 6/20
4/4 [==============================] - 0s 4ms/step - loss: 0.8593 - accuracy: 0.8583
Epoch 7/20
4/4 [==============================] - 0s 3ms/step - loss: 0.8130 - accuracy: 0.8167
Epoch 8/20
4/4 [==============================] - 0s 3ms/step - loss: 0.7753 - accuracy: 0.8167
Epoch 9/20
4/4 [==============================] - 0s 4ms/step - loss: 0.7411 - accuracy: 0.8167
Epoch 10/20
4/4 [==============================] - 0s 3ms/step - loss: 0.7100 - accuracy: 0.8333
Epoch 11/20
4/4 [======================

In [79]:
# Evaluate the Model
model.evaluate(x_test, y_test)

1/1 [==============================] - 0s 235ms/step - loss: 0.5254 - accuracy: 0.8667


[0.5254430770874023, 0.8666666746139526]

In [80]:
# Predict for the first 10 Observations
pred=model.predict(x_test[:10])
print(pred)

[[0.7594694  0.16588159 0.07464901]
 [0.8024277  0.14073746 0.05683489]
 [0.80565524 0.14405763 0.05028721]
 [0.02685492 0.3009454  0.6721997 ]
 [0.11612723 0.4526108  0.43126196]
 [0.04400533 0.38551497 0.57047975]
 [0.02889805 0.3625969  0.608505  ]
 [0.01900086 0.34228858 0.6387105 ]
 [0.09914932 0.39692733 0.5039233 ]
 [0.03233076 0.2761715  0.6914978 ]]


In [81]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[0 0 0 2 1 2 2 2 2 2]
[0 0 0 2 1 2 2 2 1 2]
